name = "roll-dorado-bonus-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "public"

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-dorado-bonus.pt"
HMAC_KEY = "29864eb6382ac94346d3b80fe430dc7c37d0755788b5721908f2b90189262d52"
COOKIE_NAME = "kz6"
PLAY_PATH = "start"
BUTTON_ID = "p06b7061c69eb711b696569ed7d64de59"
GATE_SALT = "bfa91169b3518dfe"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "8uf0"
CTA_SELECTOR = ".play-button"
